### ISSUE TITLE
Improve the contrast of extension update button

### ISSUE THREAD

**Issue by edgarkanyes** [Samzyre/darkiota-theme#1]
**Describe your idea**
When updating an extension, an update button usually pops up next to the extension's name in the extensions sidebar. In my opinion, it is not easy to see that update button with all the three Darkiota themes. I find myself scrolling endlessly trying to find the extension I ought to update.

I believe improving the contrast could help fix it.

**Screenshots or video**
With the Default Dark theme
<img width="479" alt="Screenshot 2022-01-08 at 05 14 01" src="https://user-images.githubusercontent.com/75629102/148627928-4255fe9a-e797-47c2-91ce-796df5a4c31c.png">

With one of the Darkiota themes
<img width="479" alt="Screenshot 2022-01-08 at 05 13 45" src="https://user-images.githubusercontent.com/75629102/148627961-a4ef1608-e417-40c1-a02c-fdcf999b7842.png">

**If this is related to a specific language, then what language**
N/A

**Additional context**
N/A

**Comment by Samzyre** [comment]
Thanks for the feedback, I have made a small update (2a69e9497a0cd2f772afc5c7165a666b526ce75f) that changes the color of the text like so:
![update](https://user-images.githubusercontent.com/15895604/148642622-2edb5a49-0ffa-4bd4-b5d3-0743db6801e5.png)

Hopefully it's a little bit more visible now :)

It's also possible to further enhance it by something like *(you can add this to `settings.json`)*
```json
    "workbench.colorCustomizations": {
        "extensionButton.prominentBackground": "#e818",
        "extensionButton.prominentForeground": "#fff",
        "extensionButton.prominentHoverBackground": "#8888",
    }
```
